export const TAB_CONFIG = [
  {
    id: 1,
    title: "Create Order",
    icon: "📝",
    color: "bg-indigo-600",
    permission: "create order",
  },
  {
    id: 2,
    title: "Assign Branch",
    icon: "🏢",
    color: "bg-purple-600",
    permission: "assign branch",
  },
  {
    id: 3,
    title: "Approve Order",
    icon: "✅",
    color: "bg-pink-600",
    permission: "approve order",
  },
  {
    id: 4,
    title: "Sales Order",
    icon: "📋",
    color: "bg-blue-600",
  },
  {
    id: 5,
    title: "Quotation",
    icon: "💸",
    color: "bg-sky-600",
  },
  {
    id: 6,
    title: "Deposit Slip",
    icon: "📎",
    color: "bg-emerald-600",
    permission: "deposit slip",
  },
  {
    id: 7,
    title: "Payment Confirmation",
    icon: "💳",
    color: "bg-yellow-600",
    permission: "payment confirmation",
  },
  {
    id: 8,
    title: "Invoice",
    icon: "🧾",
    color: "bg-orange-600",
    permission: "invoice",
  },
  {
    id: 9,
    title: "Collection Receipt",
    icon: "📑",
    color: "bg-cyan-600",
    permission: "collection receipt",
  },
  {
    id: 10,
    title: "Delivery",
    icon: "🚛",
    color: "bg-gray-500",
    permission: "delivery",
  },
];
